# Generated by Django 5.2.4 on 2025-07-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="follows",
            field=models.ManyToManyField(
                blank=True, related_name="followed_by", to="news.userprofile"
            ),
        ),
    ]
