# Generated by Django 5.2.4 on 2025-07-21 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_remove_userprofile_follows_userprofile_follows_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="follows_publisher",
            field=models.ManyToManyField(
                blank=True, related_name="followed_publisher", to="news.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="news.publisher",
            ),
        ),
    ]
