# Generated by Django 5.2.4 on 2025-07-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_userprofile_follows_publisher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="follows_publisher",
            field=models.ManyToManyField(
                blank=True, related_name="followed_publisher", to="news.publisher"
            ),
        ),
    ]
